const products = [
    {
        id: 1,
        name: 'Áo thun nam đen hiệu Louis Vutton',
        branch: 'Luois Vutton',
        origin: 'Hongkong',
        material: 'Polyester',
        insurance: '6',
        deli:'2',
        stock: '70',
        price:'749000',
        avatar:require('../assets/ao1.png'),
        image1:require('../assets/ao1.png'),
        image2:require('../assets/l1.jpg'),
        image3:require('../assets/l2.jpg'),                  
    },
    {
        id: 2,
        name: 'Áo thun nam đen VIP hiệu Louis Vutton',
        branch: 'Luois Vutton',
        origin: 'Hongkong',
        material: 'Polyester',
        insurance: '4',
        deli:'2',
        stock: '20',
        price:'889000',
        avatar:require('../assets/l1.jpg'),
        image1:require('../assets/l1.jpg'),
        image2:require('../assets/l3.jpg'),
        image3:require('../assets/l2.jpg'),                  
    },
    {
        id: 3,
        name: 'Áo khoác lông cừu OMBRE TREND VOGUE 1381',
        branch: 'H2T',
        origin: 'Vietnam',
        material: 'Polyester',
        insurance: '6',
        deli:'2',
        stock: '50',
        price:'965000',
        avatar:require('../assets/om1.jpg'),
        image1:require('../assets/om1.jpg'),
        image2:require('../assets/om3.jpg'),
        image3:require('../assets/om4.jpg'),                  
    },
    {
        id: 4,
        name: 'Giày Converse Chuck Taylor All Star Crater Knit',
        branch: 'Converse',
        origin: 'US',
        material: 'Leather, Rubber',
        insurance: '12',
        deli:'2',
        stock: '5',
        price:'2000000',
        avatar:require('../assets/t1.jpg'),
        image1:require('../assets/t1.jpg'),
        image2:require('../assets/t2.jpg'),
        image3:require('../assets/t3.jpg'),                  
    },
    {
        id: 5,
        name: 'Giày Converse Chuck 70 Great Next Purpose',
        branch: 'Converse',
        origin: 'US',
        material: 'Leather, Rubber',
        insurance: '12',
        deli:'2',
        stock: '5',
        price:'1900000',
        avatar:require('../assets/c1.jpg'),
        image1:require('../assets/c1.jpg'),
        image2:require('../assets/c2.jpg'),
        image3:require('../assets/c3.jpg'),                  
    },
]


export function getProducts() {
    return products;
}
export function getProduct(id) {
    return products.find((product) => (product.id == id));
}