export const ActionTypes = {
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER"
}
